### ISSUE TITLE
Desktop/mobile version

### ISSUE THREAD

**Issue by jaumard** [rxlabz/algrafx#2]
Just wondering if there is any limitation to have this only in web, would it be possible to have it on mobile/desktop too ?

**Comment by rxlabz** [comment]
Hi, globally it's only a drawing on canvas so a mobile or desktop version could be implemented. Actually I've only implemented a [web version of the exporter](https://github.com/rxlabz/algrafx/blob/master/lib/canvas_to_image_web.dart), but a mobile/desktop version would probably be even easier to write.
